name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Configure GPG Key
      run: echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg  --batch --import
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
    - name: Build with Maven
      run: mvn -B clean deploy --file pom.xml -s $GITHUB_WORKSPACE/.m2/settings.xml
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_SIGNING_KEY: ${{secrets.GPG_SIGNING_KEY}}
        SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}
        SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}
