# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/.travis/settings.xml
      env:
        GPG_EXECUTABLE: ${{ secrets.GPG_EXECUTABLE }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_SIGNING_KEY: ${{secrets.GPG_SIGNING_KEY}}
        SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}
        SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}
      
    - name: Configure GPG Key
      run: echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
      env:
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/.travis/settings.xml
      env:
        GPG_EXECUTABLE: ${{ secrets.GPG_EXECUTABLE }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        GPG_SIGNING_KEY: ${{secrets.GPG_SIGNING_KEY}}
        SONATYPE_PASSWORD: ${{secrets.SONATYPE_PASSWORD}}
        SONATYPE_USERNAME: ${{secrets.SONATYPE_USERNAME}}
        
